services:
  - type: web
    name: fortitask-frontend
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    
    # הפניה לכל הכתובות ל-index.html כדי ש-React Router יעבוד
    headers:
      - source: "/*"
        headers:
          - key: "Cache-Control"
            value: "no-cache"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  - type: web
    name: fortitask-project
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: backend
